# Generated by Django 3.0.8 on 2020-07-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='num_ratings',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
